apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: {{appName}}
build:
  artifacts:
  - image: {{appName}}
deploy:
  kubectl:
    manifests:
    - config/service.yaml
    - config/deployment.yaml
