apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: {{appName}}
build:
  artifacts:
  - image: {{appName}}
deploy:
  kubectl:
    manifests:
    - kubernetes/service.yaml
    - kubernetes/deployment.yaml
