apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{appName}}
  name: {{appName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{appName}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{appName}}
        app.kubernetes.io/part-of: {{appName}}
    spec:
      containers:
      - image: {{appName}}:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
        name: app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
